apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-prometheus-service
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 9090
    protocol: TCP
  selector:
    app: prometheus
